# Generated by Django 3.1.6 on 2021-02-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0006_auto_20210217_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aug',
            field=models.BooleanField(default=False),
        ),
    ]
